version: '3.9'
#each service is a container
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db

  photogram:
    build: "photogram/."
    restart: always
    ports:
      - 80:80
    volumes:
      - userdata:/root
      - ./photogram/photogramapp:/var/www/html
    links:
      - adminer
      - db


volumes:
  userdata:

#to run the docker-compose.yml file
#docker-compose up
#localhost:8080 for mysal adminer db 
#localhost:80 for photogram app
